cinema/urls.py
from django.conf.urls.defaults import patterns, include, url

from views import List, MovieDetails, Add, Delete, BasicInfoEdit, RatingGenreEdit

urlpatterns = patterns('',
    # Examples:
    url(r'^$', List.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', MovieDetails.as_view(), name='details'),
    url(r'^add/$', Add.as_view(), name='add'),
    url(r'^delete/(?P<pk>\d+)/$', Delete.as_view(), name='delete'),
    url(r'^basic_info/(?P<pk>\d+)/$', BasicInfoEdit.as_view(), name='edit_basic_info'),
    url(r'^rating_and_genre/(?P<pk>\d+)/$', RatingGenreEdit.as_view(), name='edit_rating_and_genre'),
    url(r'^crew_and_cast/(?P<pk>\d+)/$', BasicInfoEdit.as_view(), name='edit_crew_and_cast'),
    url(r'^sales_info/(?P<pk>\d+)/$', BasicInfoEdit.as_view(), name='edit_sales_info'),
    url(r'^art/(?P<pk>\d+)/$', BasicInfoEdit.as_view(), name='edit_art'),
    url(r'^feature_and_trailer/(?P<pk>\d+)/$', BasicInfoEdit.as_view(), name='edit_feature_and_trailer'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('cinema.urls')),
    url(r'^', include('django.contrib.auth.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

cinema/models.py
from django.db import models
from django.core.urlresolvers import reverse

from django.contrib.auth.models import User

from django_extensions.db.models import TimeStampedModel

class iTunesProvider(models.Model):
    name = models.CharField(max_length=100, unique=True)
    
    def __unicode__(self):
        return self.name
    
    class Meta():
        verbose_name = 'iTunes Provider'
        verbose_name_plural = 'iTunes Providers'
    
class Movie(TimeStampedModel):
    MOVIE_TYPES = {'film':'Film', 'tv':'Tv', 'asset':'Asset'}.items()

    movie_type = models.CharField(max_length=10, choices = MOVIE_TYPES)
    title = models.CharField(max_length=100)
    provider = models.CharField(max_length=100, blank=True)
    itunes_provider = models.ForeignKey(iTunesProvider, null=True, blank=True)
    
    metadata_language = models.CharField(max_length=100, blank=True)
    vendor_id = models.CharField(max_length=100, blank=True)
    origin_country = models.CharField(max_length=100, blank=True)
    original_locale = models.CharField(max_length=100, blank=True, help_text = 'Original spoken locale of movie')
    copyright = models.CharField(max_length=100, blank=True)
    production_company = models.CharField(max_length=100, blank=True)
    theatrical_release_date_NA = models.BooleanField(default=True)
    theatrical_release_date = models.DateField(null=True, blank=True)
    synopsis = models.TextField(blank=True)
    
    is_complete = models.BooleanField(default=False)
    
    created_by = models.ForeignKey(User, related_name='created_records')
    modified_by = models.ForeignKey(User, related_name='modified_records')
    
    def get_absolute_url(self):
        return reverse('details', kwargs={'pk': self.pk})
    
    def __unicode__(self):
        return self.title

class BaseEnumerable(models.Model):
    title = models.CharField(max_length = 100, primary_key=True)
    
    class Meta:
        ordering = ('title',)
        abstract = True

    def __unicode__(self):
        return self.title

class Territory(BaseEnumerable):
    pass

class RatingSystem(BaseEnumerable):
    pass

class PriceTier(BaseEnumerable):
    pass

class Rating(models.Model):
    value = models.CharField(max_length = 100)
    system = models.ForeignKey(RatingSystem)
    
    class Meta:
        unique_together = ( ('value', 'system'), )

    def __unicode__(self):
        return self.value + ' - ' + self.system_id

class MovieRating(models.Model):
    movie = models.ForeignKey(Movie, related_name='ratings')
    rating = models.ForeignKey(Rating)
    territory = models.ForeignKey(Territory)
    reason = models.CharField(max_length = 100, blank=True)
    price_tier = models.ForeignKey(PriceTier)
    
    def __unicode__(self):
        return '%s - %s (rating=%s, related for=%s, Price Tier=%s)' % (
            self.movie, self.territory_id, self.rating, self.reason, self.price_tier_id)

class Genre(BaseEnumerable):
    pass

class MovieGenre(models.Model):
    movie = models.ForeignKey(Movie, related_name='genres')
    genre = models.ForeignKey(Genre)

    def __unicode__(self):
        return unicode(self.movie) + ' - ' + self.genre_id

cinema/forms.py
from django import forms
from django.forms.models import inlineformset_factory

from models import Movie, MovieRating, MovieGenre

class BaseModelForm(forms.ModelForm):
    error_css_class = 'error'

class BasicInfo(BaseModelForm):
    def __init__(self, *args, **kwargs):
        super(BasicInfo, self).__init__(*args, **kwargs)
        self.fields['itunes_provider'].label = "Provider (for iTunes)"
        self.fields['itunes_provider'].help_text = 'For example, select "premiere" if provider is "Distribber"'
        self.fields['metadata_language'].label = "Language of Metadata"
        self.fields['vendor_id'].label = "Vendor ID"
        self.fields['origin_country'].label = "Country of Origin"
        self.fields['original_locale'].label = "Original Spoken Locale of Movie"
        self.fields['theatrical_release_date_NA'].label = "Check if N/A"
    
    class Meta:
        model = Movie
        fields = (
            'movie_type', 'title', 'provider', 'itunes_provider', 'metadata_language',
            'vendor_id', 'origin_country', 'original_locale', 'copyright',
            'production_company', 'theatrical_release_date_NA', 'theatrical_release_date', 'synopsis',
        )

class MovieRatingForm(BaseModelForm):
    class Meta:
        model = MovieRating

class MovieGenreForm(BaseModelForm):
    class Meta:
        model = MovieGenre

MovieRatingFormset = inlineformset_factory(parent_model=Movie, model=MovieRating, form=MovieRatingForm, extra=1)
MovieGenreFormset = inlineformset_factory(parent_model=Movie, model=MovieGenre, form=MovieGenreForm, max_num=3, extra=3)

cinema/views.py
import operator

from django.views.generic import UpdateView, ListView, DetailView, CreateView, DeleteView
from django.db.models import Q
from django.core.urlresolvers import reverse

from django.contrib.messages import success, error

from models import Movie
from forms import BasicInfo as BasicInfoForm, MovieRatingFormset, MovieGenreFormset
from view_utils import LoginRequiredMixin, AddPermissionMixin, ChangePermissionMixin, DeletePermissionMixin 
from view_utils import MultipleFormsView, BaseMovieFormMixin, BaseMovieFormsMixin

class List(LoginRequiredMixin, ListView):
    template_name = 'list.html'
    paginate_by = 50
    search_fields = 'title'.split(',')

    def get_queryset(self):
        'applies keyword search'
        query = Movie.objects.all()
        search_phrase = self.request.REQUEST.get('search', None)
        if search_phrase:
            for bit in search_phrase:
                orm_lookups = ["%s__icontains" % search_field for search_field in self.search_fields]
                or_queries = [Q(**{orm_lookup: bit}) for orm_lookup in orm_lookups]
                query = query.filter(reduce(operator.or_, or_queries))
        return query      

class MovieDetails(LoginRequiredMixin, DetailView):
    template_name = 'details.html'
    model = Movie

class Add(BaseMovieFormMixin, AddPermissionMixin, CreateView):
    template_name = 'basic_info.html'
    form_class = BasicInfoForm
    get_next_url = lambda self: reverse('edit_rating_and_genre', kwargs={'pk': self.object.pk})

class Delete(DeletePermissionMixin, DeleteView):
    template_name = 'delete.html'
    model = Movie
    
    def get_success_url(self):
        success(self.request, "Movie '%s' was removed successfully" % self.object)
        return reverse('list')

class BasicInfoEdit(BaseMovieFormMixin, ChangePermissionMixin, UpdateView):
    template_name = 'basic_info.html'
    form_class = BasicInfoForm
    get_next_url = lambda self: reverse('edit_rating_and_genre', kwargs={'pk': self.object.pk})

class RatingGenreEdit(BaseMovieFormsMixin, ChangePermissionMixin, MultipleFormsView):
    'differs by multiple formset on the page'
    
    template_name = 'rating_and_genre.html'
    get_next_url = lambda self: reverse('edit_crew_and_cast', kwargs={'pk': self.object.pk})
    form_classes = {
        'ratings': MovieRatingFormset,
        'genres': MovieGenreFormset,
    }

cinema/templates/base_form.html
{% extends 'base.html' %}

{% block extra_tabs %}
    {% autoescape off %}
        <li{{ step1|yesno:' class="active",' }}><a href="{% url edit_basic_info object.pk %}">Basic Info</a></li>
        <li{{ step2|yesno:' class="active",' }}><a href="{% url edit_rating_and_genre object.pk %}">Rating and Genre</a></li>
        <li{{ step3|yesno:' class="active",' }}><a href="{% url edit_crew_and_cast object.pk %}">Crew and Cast</a></li>
        <li{{ step4|yesno:' class="active",' }}><a href="{% url edit_sales_info object.pk %}">Sales Info</a></li>
        <li{{ step5|yesno:' class="active",' }}><a href="{% url edit_art object.pk %}">Chapter and Poster Art</a></li>
        <li{{ step6|yesno:' class="active",' }}><a href="{% url edit_feature_and_trailer object.pk %}">Feature and Trailer</a></li>
    {% endautoescape %}
{% endblock %}

cinema/templates/base_form_buttons.html
{% spaceless %}
    {# typical button/link set for metadata forms #}
    <hr/>
    
    <div class="btn-toolbar">
        <div class="btn-group">
            {% if not previous_off %}
                <button type="submit" class="btn" name="previous"><i class="icon-arrow-left icon-white"></i> Previous</button>
            {% endif %}
            
            {% if not save_off %}
                <button type="submit" class="btn">{% firstof save_text 'Save' %}</button>
            {% endif %}
        </div>
        
        <div class="btn-group">
            {% if not reset_off %}
                <a class="btn btn-inverse" href="./"><i class="icon-refresh icon-white"></i> Reset changes</a>
            {% endif %}
        </div>
        
        <div class="btn-group pull-right">
            {% if finish %}
                <button type="submit" class="btn btn-success" name="finish">Finish</button>
            {% else %}
                {% if not next_off %}
                    <button type="submit" class="btn btn-primary" name="next">Next <i class="icon-arrow-right icon-white"></i></button>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endspaceless %}

cinema/templates/basic_info.html
{% extends 'base_form.html' %}
{% load bootstrap widget_tweaks %}

{% block title %}{{ form.instance.pk|yesno:'Basic Info,Add,Add' }}{% endblock %}

{% block extra_tabs %}
    {% if form.instance.pk %}
        {% with 1 as step1 %}
            {{ block.super }}
        {% endwith %}
    {% else %}
        <li class="active"><a href="{% url add %}">Add</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row">
        <form action="./" method="post" class="edit_form span10 js_active_form">
            {% csrf_token %}
            
            <fieldset class="form-inline">
                <span class="control-group {{ form.movie_type.css_classes }}">
                    This input is for
                    <span class="controls">
                        {{ form.movie_type|attr:"required:required"|add_class:"input-small" }}
                        {% if form.movie_type.errors %}
                            <span class="help-inline">{{ form.movie_type.errors.as_text|linebreaksbr }}</span>
                        {% endif %}
                    </spafieldsetn>
                </span>
            </fieldset>
            
            <hr/>
            
            <h3>Step 1 of 6 - Basic Info</h3>
            <fieldset class="form-horizontal">
                {{ form.title|attr:"required:required"|bootstrap }}
                {{ form.provider|bootstrap }}
                {{ form.itunes_provider|bootstrap }}
                {{ form.metadata_language|bootstrap }}
                {{ form.vendor_id|bootstrap }}
                {{ form.origin_country|bootstrap }}
                {{ form.original_locale|bootstrap }}
                {{ form.copyright|bootstrap }}
                {{ form.production_company|bootstrap }}
                
                {# <!--theatrical_release_date--> #}
                {% with release_date=form.theatrical_release_date release_date_NA=form.theatrical_release_date_NA %}
                    <div class="control-group {{ release_date.css_classes }}">
                        <label class="control-label">{{ release_date.label }}</label>
                        <div class="controls">
                            {{ release_date|add_class:"js_datepicker" }}
                            {% if release_date.errors %}
                                <span class="help-inline">
                                    {{ release_date.errors.as_text|linebreaksbr }}
                                </span>
                            {% endif %}
                            
                            &nbsp;
                            <label class="checkbox inline">{{ release_date_NA }}<span>{{ release_date_NA.label }}</span></label>
                        </div>
                    </div>
                {% endwith %}
                
                {{ form.synopsis|add_class:"input-block-level"|bootstrap }}
            </fieldset>
            
            {% if form.instance.pk %}
                {% include 'base_form_buttons.html' with previous_off=1 only %}
            {% else %}
                {% include 'base_form_buttons.html' with save_text='Create and Add more' only %}
            {% endif %}
        </form>
    </div>
{% endblock %}

{% block endjs %}
    <script type="text/javascript">
        var $theatrical_release_date = $('#id_theatrical_release_date');
        $('#id_theatrical_release_date_NA').change(function(){
            if (this.checked){
                $theatrical_release_date.attr('disabled', 'disabled');
            } else {
                $theatrical_release_date.removeAttr('disabled');
            }
        }).change();
    </script>
{% endblock %}

cinema/templates/delete.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block title %}Delete {{ object.title }}{% endblock %}

{% block extra_tabs %}
    <li class="active"><a href="{% url delete object.pk %}">Delete</a></li>
{% endblock %}

{% block content %}
    <h2>Are you sure?</h2>
    <div class="row">
        <form action="./" method="post" class="well span4">
            {% csrf_token %}
            <p>Are you sure you want to delete '{{ object.title }}' movie and all related records?</p>
            
            <p>
                <a class="btn" href="{% url list %}">Cancel</a>
                <button type="submit" class="btn btn-danger pull-right"><i class="icon-trash icon-white"></i> Confirm</button>
            </p>
        </form>
    </div>
{% endblock %}

cinema/templates/details.html
{% extends 'base.html' %}

{% block title %}{{ object.title }}{% endblock %}

{% block extra_tabs %}
    <li class="active"><a href="{% url details object.pk %}">Details</a></li>
{% endblock %}

{% block content %}{% spaceless %}{% with perms.cinema.change_movie as can_change %}
    <p>Metadata information for: <b>{{ object.title }}</b></p>
    
    <h3>Basic Info</h3>
    {% if can_change %}<a class="edit_link" href="{% url edit_basic_info object.pk %}">Edit</a>{% endif %}
    <dl class="info">
        <dt>Title:</dt><dd>{{ object.title }}</dd>
        <dt>Provider:</dt><dd>{{ object.provider }}</dd>
        <dt>Provider (for iTunes):</dt><dd>{{ object.itunes_provider }}</dd>
        <dt>Language of Metadata:</dt><dd>{{ object.metadata_language }}</dd>
        <dt>Vendor ID:</dt><dd>{{ object.vendor_id }}</dd>
        <dt>Country of Origin:</dt><dd>{{ object.origin_country }}</dd>
        <dt>Copyright:</dt><dd>{{ object.copyright }}</dd>
        <dt>Production Company:</dt><dd>{{ object.production_company }}</dd>
        {% if not object.theatrical_release_date_NA %}
            <dt>Theatrical Release Date:</dt><dd>{{ object.theatrical_release_date|date:"Y/m/d" }}</dd>
        {% endif %}
        <dt>Synopsis:</dt><dd>{{ object.synopsis }}</dd>
    </dl>

    <h3>Territory, Rating and Genre</h3>
    {% if can_change %}<a class="edit_link" href="{% url edit_rating_and_genre object.pk %}">Edit</a>{% endif %}
    <dl class="info">
        <dt>Territory:</dt>
        <dd>
            {% for rating in object.ratings.all %}
                {{ rating.territory_id }} (rating={{ rating.rating.value }},
                    related for={{ rating.reason }},
                    rating system={{ rating.rating.system }},
                    Price Tier={{ rating.price_tier_id }})
                {% if not forloop.last %}<br/>{% endif %}
            {% endfor %}
        </dd>
                    
        <dt>Genre:</dt>
        <dd>
            {% for genre in object.genres.all %}
                {{ genre.genre_id|capfirst }}
                {% if not forloop.last %}<br/>{% endif %}
            {% endfor %}
        </dd>
    </dl>

    <h3>Crew and Cast</h3>
    {% if can_change %}<a class="edit_link" href="{% url edit_crew_and_cast object.pk %}">Edit</a>{% endif %}
    <dl class="info">
        <dt>Crew:</dt><dd>{{ object }}</dd>
        <dt>Cast:</dt><dd>{{ object }}</dd>
    </dl>

    <h3>Sales Info</h3>
    {% if can_change %}<a class="edit_link" href="{% url edit_sales_info object.pk %}">Edit</a>{% endif %}
    <dl class="info">
        <dt>Cleared for Sale:</dt><dd>{{ object }}</dd>
        <dt>Sales Start Date:</dt><dd>{{ object }}</dd>
        <dt>Sales End Date:</dt><dd>{{ object }}</dd>
        <dt>Cleared for VOD:</dt><dd>{{ object }}</dd>
        <dt>VOD Type:</dt><dd>{{ object }}</dd>
        <dt>Physical Release Date:</dt><dd>{{ object }}</dd>
    </dl>

    <h3>Chapter and Poster Art</h3>
    {% if can_change %}<a class="edit_link" href="{% url edit_art object.pk %}">Edit</a>{% endif %}
    <dl class="info">
        <dt>iTunes Poster Art:</dt><dd>{{ object }}</dd>
        <dt>Chaptering:</dt><dd>{{ object }}</dd>
    </dl>

    <h3>Feature and Trailer</h3>
    {% if can_change %}<a class="edit_link" href="{% url edit_feature_and_trailer object.pk %}">Edit</a>{% endif %}
    <dl class="info">
        <dt>Feature Crop Top:</dt><dd>{{ object }}</dd>
        <dt>Feature Crop Bottom:</dt><dd>{{ object }}</dd>
        <dt>Feature Crop Left:</dt><dd>{{ object }}</dd>
        <dt>Feature Crop Right:</dt><dd>{{ object }}</dd>
        <dt>Feature Spoken Language:</dt><dd>{{ object }}</dd>
        <dt>Feature Subtitles:</dt><dd>{{ object }}</dd>
        <dt>Feature Forces Narrative:</dt><dd>{{ object }}</dd>
        <dt>Feature Additional Assets:</dt><dd>{{ object }}</dd>
        <dt>Trailer Crop Top:</dt><dd>{{ object }}</dd>
        <dt>Trailer Crop Bottom:</dt><dd>{{ object }}</dd>
        <dt>Trailer Crop Left:</dt><dd>{{ object }}</dd>
        <dt>Trailer Crop Right:</dt><dd>{{ object }}</dd>
        <dt>Trailer Spoken Language:</dt><dd>{{ object }}</dd>
        <dt>Trailer Subtitles:</dt><dd>{{ object }}</dd>
        <dt>Trailer Forces Narrative:</dt><dd>{{ object }}</dd>
        <dt>Trailer Additional Assets:</dt><dd>{{ object }}</dd>
    </dl>
{% endwith %}{% endspaceless %}{% endblock %}

cinema/templates/inline_form_field.html
{% spaceless %}{% load widget_tweaks %}
{# <!--Displays field of inline form in the table. Expects params 'field', 'classes' and 'attrs' --> #}

<td class="control-group {{ field.css_classes }}" {% if field.errors %}title="{{ field.errors.as_text }}"{% endif %}>
    {% if attrs %}
        {{ field|add_class:classes|attr:attrs }}
    {% else %}
        {{ field|add_class:classes }}
    {% endif %}
</td>

{% endspaceless %}

cinema/templates/list.html
{% extends 'base.html' %}

{% block title %}All items{% endblock %}

{% block content %}{% spaceless %}

    {% if request.REQUEST.search %}
        <h3>Search results for '{{ request.REQUEST.search }}'</h3>
    {% endif %}
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th>Added</th>
                <th>Added By</th>
                <th>Last Modified</th>
                <th>Modified By</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.title }}</td>
                <td>{{ item.created|date:"m/d/Y" }}</td>
                <td>{{ item.created_by }}</td>
                <td>{{ item.modified|date:"m/d/Y" }}</td>
                <td>{{ item.modified_by }}</td>
                {% if item.is_complete %}
                    <td class="green">Complete</td>
                {% else %}
                    <td class="red">Incomplete</td>
                {% endif %}
                <td>
                    <a href="{{ item.get_absolute_url }}">View</a>
                    {% if perms.cinema.change_movie %}&nbsp;|&nbsp;<a href="{% url edit_basic_info item.pk %}">Edit</a>{% endif %}
                    {% if perms.cinema.delete_movie %}&nbsp;|&nbsp;<a href="{% url delete item.pk %}">Delete</a>{% endif %}
                </td>
            </tr>
            {% empty %}
                <tr><td colspan="7">List is empty</td></tr>
            {% endfor %}
        </tbody>
    </table>
    
    <ul class="pager">
        <li class="previous {% if not is_paginated or not page_obj.has_previous %}disabled{% endif %}">
            <a href="./?page={{ page_obj.previous_page_number }}">&larr; Previous</a>
        </li>
        <li>page #{{ page_obj.number }} of {{ paginator.num_pages }}</li>
        <li class="next {% if not is_paginated or not page_obj.has_next %}disabled{% endif %}">
            <a href="./?page={{ page_obj.next_page_number }}">Next &rarr;</a>
        </li>
    </ul>
{% endspaceless %}{% endblock %}

templates/base.html
<!doctype html>{% spaceless %}{% url list as list_url %}
<html class="no-js" lang="en">
    <head>
        <!-- META -->
        
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock %} | PDS</title>
        <meta name="description" content="{% block metadescription %}{% endblock %}">
        <meta name="keywords" content="{% block metakeywords %}{% endblock %}">
        <meta name="author" content="{% block metaauthor %}{% endblock %}">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.ico" type="image/x-icon">

        <!-- CSS -->
        <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/bootstrap.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/bootstrap-responsive.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/datepicker.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}style.css">
        {% block forestyle %}{% endblock %}

        <!-- JS -->
        
        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        {% block forejs %}{% endblock %}
        
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="/" title="PDS">PDS</a>
                    {% block navigation %}
                        <div class="nav-collapse">
                            <form class="navbar-search pull-right" method="get" action="{{ list_url }}">
                                <input type="text" class="search-query span2" placeholder="Search" name="search">
                            </form>
                            <ul class="nav pull-right">
                                {% if request.user.is_authenticated %}
                                    <li><a href="{{ list_url }}">List</a></li>
                                    {% if request.user.is_staff %}
                                        <li><a href="{% url admin:index %}">Admin</a></li>
                                    {% endif %}
                                    <li><a href="{% url password_change %}">Change password</a></li>
                                    <li><a href="{% url logout %}">Logout</a></li>
                                {% endif %}
                            </ul>
                        </div><!--/.nav-collapse -->
                    {% endblock %}
                </div>
            </div>
        </div>  

        <div class="container">
            {% block tabs %}
                <ul class="nav nav-tabs">
                    <li {% if request.path == list_url %}class="active"{% endif %}>
                        <a href="{{ list_url }}">List</a>
                    </li>
                    {% block extra_tabs %}
                        {% if perms.cinema.add_movie %}<li><a href="{% url add %}">Add</a></li>{% endif %}
                    {% endblock %}
                </ul>
            {% endblock %}
            
            {% block user_messages %}
                {% for message in messages %}
                    <div class="alert {% for tag in message.tags %}alert-{{ tag }}{% endfor %}">
                        <a class="close" data-dismiss="alert" href="#">×</a>
                        {{ message|safe }}
                    </div>
                {% endfor %}
                
                {% if error_message %}
                    <div class="alert alert-error">
                        <a class="close" data-dismiss="alert" href="#">×</a>
                        {{ error_message|safe }}
                    </div>
                {% endif %}

                {% if success_message %}
                    <div class="alert alert-success">
                        <a class="close" data-dismiss="alert" href="#">×</a>
                        {{ success_message|safe }}
                    </div>
                {% endif %}            
            {% endblock %}

            {% block content %}{% endblock %}
        </div>

        <footer>
            <hr/>
            <p class="copyright pull-right">&copy; 2012 Level Up Developers. All rights reserved</p>
        </footer>

        <script type='text/javascript' src="{{ STATIC_URL }}jquery-1.7.2.js"></script>
        <!--[if lt IE 7 ]>
            <script type='text/javascript' src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
            <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
        <![endif]-->
        <script type='text/javascript' src="{{ STATIC_URL }}bootstrap/bootstrap-alert.js"></script>
        <script type='text/javascript' src="{{ STATIC_URL }}bootstrap/bootstrap-datepicker.js"></script>
        <script type='text/javascript' src="{{ STATIC_URL }}bootstrap/bootstrap-tooltip.js"></script>
        
        <script type="text/javascript">
            $(".alert").alert();
            $('.js_datepicker').datepicker({'format': 'yyyy-mm-dd'});
            
            // errors for inline forms are displayed via tooltip
            $('.error[title]').tooltip();
            
            {# activate first input or select #}
            $('.js_active_form input[type!=hidden]:first, .js_active_form select:first').first().focus();
        </script>
        {% block endjs %}{% endblock %}

    </body>
{% endspaceless %}</html>